const express = require('express')
const adminRoutes = require('./routes/admin')
const shopRoutes = require('./routes/shop')
const bodyParser = require('body-parser')
const app = express()
app.use(bodyParser.urlencoded({extended: false}))
app.use('/shops',adminRoutes)
app.use('/shops',shopRoutes)
app.use((req, res, next) => {
    res.status(404).send('<h1>page not found</h1>')
})
app.listen(4000)