const path = require('path')
const express = require('express')
const adminRoutes = require('./routes/admin')
const shopRoutes = require('./routes/shop')
const bodyParser = require('body-parser')
const { join } = require('path')
const app = express()
app.use(bodyParser.urlencoded({extended: false}))
app.use('/shops',adminRoutes)
app.use('/shops',shopRoutes)
app.use((req, res, next) => {
    res.status(404).sendFile(path.join(__dirname, './', 'views', 'pagenotfound.html'))
})
app.listen(4000)