const path = require('path')
const express = require('express')
const adminRoutes = require('./routes/admin')
const shopRoutes = require('./routes/shop')
const bodyParser = require('body-parser')
const errorRoutes = require('./routes/error')
const contactRoutes = require('./routes/contact')
const { join } = require('path')
const app = express()
app.use(bodyParser.urlencoded({extended: false}))
app.use(express.static(path.join(__dirname, 'public')))
app.use('/shops',adminRoutes)
app.use('/shops',shopRoutes)
app.use('/contact',contactRoutes)
app.use(errorRoutes)
app.listen(4000)